### ISSUE TITLE
Creating Firebase lisnters for main_button

### ISSUE THREAD

**Issue by MMurph3y** [dylcarinc/click_plus_plus#2]
Need to add critical code to app_state that will allow the app to communicate with the database. We want to make sure that we are not live updating the count, rather, we need to keep two ints:

- One int that is the pulled int that is saved to the account, which is the initial display

- Then one that is a local int that then will display after the intial, and will only be applied to the account after either loging out or switching pages

So we need to have a listners in some class then be able to pull the ints to the page_button.

**Comment by Jkwashu** [comment]
Fixed in basic implementation, button now communicates with the scoreboard on firebase and keeps track of account score.
